env: "local"

server:
  address: ":8080"

db:
  url: "postgres://postgres:postgres@postgres:5432/url_shortener"
  name: "url_shortener"
  password: "postgres"
  max_opens_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 3600s
  conn_max_idle: 600s

kafka:
  brokers:
    - "kafka:9092"
  topic: "url-events"

url:
  base: "http://localhost:8080/"
  code_length: 8
  code_alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  default_ttl: 87600h

logger:
  level: "debug"
  show_path_call: true
